dist: xenial
language: c
os:
  - linux
compiler: gcc-5
env:
  global:
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    #
    # GH_TOKEN: @marvim Github token
    - secure: N73UKR9bIcAh5q+YXdru8iWdMJh6V85PMtl14ZK4EzTi1MP8AcSuTEJMOAizGOcYL+jL7tM/Kd8rxsJVYcwdqIPij4jugNsm4UZLgxAoI1rZ2wpUHAqQdknTFGzss64UuNehbcEM82aK5/qbtvzU3eM8UVVVsuTg8SvB+XAmdI4=
    # COVERITY_SCAN_TOKEN
    - secure: pgI3Qt7bCRDeuKX38hP9xTJ6CdbwoUkcPToHnfDFYeclhUJRgCfZhCKKO+zTwqoa2Jx7wShoFeHaKidOFctg4ls4lrn47b0bPFED3LtU7RDQaeamqFKzgTV1IcEpkUfGl/i8tOmaEd7UvyUHKuKZmjmVr4Ce4ugATShYB186EW0=
matrix:
  include:
    - env: CI_TARGET=assign-labels
    - env: CI_TARGET=auto-pullrequest
      # For nvim.appimage
      # (until https://github.com/neovim/neovim/issues/7537 is fixed)
      sudo: true
    - env: CI_TARGET=deps-src
    - env: CI_TARGET=doc-index
    - env: CI_TARGET=doxygen
    - env: CI_TARGET=sync-mirrors
    - env: CI_TARGET=sync-lp-mirrors
    - env: CI_TARGET=translation-report
    - env: CI_TARGET=user-docu
    - env: CI_TARGET=vimpatch-report
    - env: CI_TARGET=clint-errors
    - os: linux
      env: CI_TARGET=pvs-report
      compiler: clang
    - os: linux
      env: CI_TARGET=clang-report SCAN_BUILD=scan-build
      compiler: clang
    - os: osx
      osx_image: xcode9.4  # Keep in sync with neovim/neovim's osx_image
      env: CI_TARGET=nightly
      compiler: clang
    - env: CI_TARGET=nightly
      sudo: true
#    - os: linux
#      env: CI_TARGET=coverity
#  allow_failures:
#    - os: linux
#      env: CI_TARGET=coverity
install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install bash;
      brew install jq;
    fi;
    printf "machine github.com login ${GH_TOKEN:-unknown} password x-oauth-basic\n" >> "$HOME/.netrc";
    printf "machine api.github.com login ${GH_TOKEN:-unknown} password x-oauth-basic\n" >> "$HOME/.netrc";
    printf "machine uploads.github.com login ${GH_TOKEN:-unknown} password x-oauth-basic\n" >> "$HOME/.netrc";
script:
  - ./ci/${CI_TARGET}.sh
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - build-essential
      - cmake
      - fuse  # for AppImage
      - g++-5
      - gcc-5
      - gdb
      - git-remote-bzr
      - libtool
      - libtool-bin
      - pkg-config
      - unzip
      - xclip
cache:
  apt: true
  directories:
    - "${TRAVIS_BUILD_DIR}/.deps/build/src"

notifications:
  email:
    on_success: never
