sudo: false
language: c
os:
  - linux
compiler: gcc-5
env:
  global:
    # Encrypted environment variables, see
    # http://docs.travis-ci.com/user/encryption-keys/
    #
    # GH_TOKEN: Marvim's Github access token
    - secure: OyoqXO0CqQJpxggE0tNi6LeYXGHslw4SSe4u3UbTOali5AbKdRnSxkMz9YQiuEajJDI2//LZef6RVLULFPZqzIOzsr4yi9S1fbPhXHvqtnZOkpamnkXNNCf7Fd6vGJtT1W140YR9woQoSk0bcLepawSdtkgp+n/ZSqY8rvADgqw=
    # COVERITY_SCAN_TOKEN
    - secure: pgI3Qt7bCRDeuKX38hP9xTJ6CdbwoUkcPToHnfDFYeclhUJRgCfZhCKKO+zTwqoa2Jx7wShoFeHaKidOFctg4ls4lrn47b0bPFED3LtU7RDQaeamqFKzgTV1IcEpkUfGl/i8tOmaEd7UvyUHKuKZmjmVr4Ce4ugATShYB186EW0=
  matrix:
    - CI_TARGET=assign-labels
    - CI_TARGET=deps-src
    - CI_TARGET=doc-index
    - CI_TARGET=doxygen
    - CI_TARGET=nightly
    - CI_TARGET=sync-mirrors
    - CI_TARGET=translation-report
    - CI_TARGET=user-docu
    - CI_TARGET=vimpatch-report
    - CI_TARGET=clint-errors
matrix:
  include:
    - env: CI_TARGET=clang-report SCAN_BUILD=scan-build-3.6
      compiler: clang-3.6
    - os: osx
      env: CI_TARGET=deps64
      compiler: clang
    - env: CI_TARGET=coverity
      compiler: gcc
  allow_failures:
    - env: CI_TARGET=coverity
      compiler: gcc
install:
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install bash;
    fi
script:
  - ./ci/${CI_TARGET}.sh
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      # Basic Neovim/test dependencies.
      - autoconf
      - automake
      - build-essential
      - cmake
      - gdb
      - libtool
      - pkg-config
      - unzip
      - xclip
      # Additional compilers/tools.
      - clang-3.6
      - g++-5
      - gcc-5
      - llvm-3.6-dev
      # Tools required for bot-ci.
      - bzr-fastimport
cache:
  apt: true
  directories:
    - "${TRAVIS_BUILD_DIR}/.deps/build/src"

notifications:
  email:
    on_success: never
